name: Build and release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, fedora-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2.8.2
        with:
          ghc-version: 9.6.4
          enable-stack: true

      - name: Build the executable
        run: |
          mkdir dist
          stack install --local-bin-path dist

      - name: Rename executable (Ubuntu)
        run: |
          mv dist/reservant dist/reservant-ubuntu
        if: matrix.os == 'ubuntu-latest'
        shell: bash

      - name: Rename executable (Fedora)
        run: |
          mv dist/reservant dist/reservant-fedora
        if: matrix.os == 'fedora-latest'
        shell: bash

      - name: Rename executable (MacOS)
        run: |
          mv dist/reservant dist/reservant-macos
        if: matrix.os == 'macos-latest'
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v5

      - name: Make the artifact executable
        run: chmod u+x dist/reservant-* || true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            reservant-ubuntu
            reservant-fedora
            reservant-macos
